export const LOAD_BLOGS_SUCCESS = "LOAD_BLOGS_SUCCESS";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const DELETE_BLOG_OPTIMISTIC = "DELETE_BLOG_OPTIMISTIC";